### ISSUE TITLE
Layers do not extend to the bottom of the screen [BUG]

### ISSUE THREAD

**Issue by silo8811** [Rebmiami/Territect#14]
**Describe the bug**
Layers not going to bottom of screen
**To Reproduce**
Only lets you draw 600px on padding/uniform, when there are more pixels on the bottom of the screen

**Expected behavior**
Would like to see the pixels being drawn to the entire screen
**Screenshots**
![image](https://user-images.githubusercontent.com/116988999/207369033-e0010754-a55e-4894-a860-109e08e99dd5.png)

**Platform**
96.2.350
Windows

**Comment by Rebmiami** [comment]
Use "Settle Height" in the pass settings to draw at the bottom of the screen. Set this to 4 to draw right above the WALL at the bottom of the screen.
![image](https://user-images.githubusercontent.com/59275598/207370070-18cba206-105c-497e-90b3-57b55d94e8dc.png)
