### ISSUE TITLE
Distance from the bottom of the scene is measured incorrectly [BUG]

### ISSUE THREAD

**Issue by Jakav-N** [Rebmiami/Territect#28]
**Describe the bug**
Territect measures distance from the bottom of the scene from the actual bottom of the scene. Usually, this would not be a problem, but because nothing can be in the bottom 4 pixels of the scene this is an actual problem. Usually, wall edge mode is used with Territect, and because of this a few pixels of any creation will be deleted when the settle height is less than 4.

**To Reproduce**
The following script shows this behavior well, as no water is created.
```json
{"name":"Gravity-Based Generation", "data":"{\"versionMinor\":0, \"versionMajor\":1, \"passes\":[{\"bottom\":0, \"layers\":[{\"type\":2, \"variation\":0, \"mode\":1, \"thickness\":4}, {\"type\":44, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":133, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":5, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":30, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":187, \"variation\":5, \"mode\":1, \"thickness\":15}, {\"type\":47, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":73, \"variation\":5, \"mode\":1, \"thickness\":5}, {\"type\":157, \"variation\":0, \"mode\":2, \"thickness\":5}, {\"type\":28, \"variation\":0, \"mode\":1, \"thickness\":2}], \"settleTime\":120}, {\"bottom\":0, \"layers\":[{\"preserveProps\":false, \"oldType\":28, \"inExisting\":true, \"type\":44, \"percent\":100, \"mode\":4, \"inLayer\":false}], \"settleTime\":0}]}"}
```

**Expected behavior**
I would expect Territect to instead measure from 4 pixels above the bottom of the simulation, except for presets created in older versions where this may or may not be better.

**Platform (please complete the following information):**
I believe this affects all platforms, though I have not tested except in my environment.

**Comment by Rebmiami** [comment]
Fixed by offsetting the value stored and the value displayed by 4. This will preserve full compatibility with older presets and also allow for you to input values down to -4 in case there's any reason you might want this original behavior. I also realized that there's no upper cap on these values, which I should probably fix.

**Comment by Jakav-N** [comment]
That seems good. I'll close as completed.
