### ISSUE TITLE
Errors caused by deprecated TPT Lua API functions [BUG]

### ISSUE THREAD

**Issue by Maticzpl** [Rebmiami/Territect#34]
**Describe the bug**
As of The Powder Toy 98.0 functions like `tpt.confirm`, `tpt.message_box`, `tpt.input` have been deprecated and replaced by [`ui.beginConfirm`](https://powdertoy.co.uk/Wiki/W/Lua_API:Interface.html#interface.beginConfirm), [`ui.beginMessageBox`](https://powdertoy.co.uk/Wiki/W/Lua_API:Interface.html#interface.beginMessageBox), [`ui.beginInput`](https://powdertoy.co.uk/Wiki/W/Lua_API:Interface.html#interface.beginInput).

E.g.
When importing a preset from a save this error appears:
`scripts/downloaded/237 Rebmiami-Territect.lua:1089: attempt to call field 'confirm' (a nil value)`

Besides this one error there are more places in territect's code where deprecated functions can cause errors which I didn't bother checking and reporting individually.

**To Reproduce**
1. Go to a save containing a Territect preset. E.g. `id:2960170`.
2. Click on one of the squares with the territect logo.
3. See error

**Expected behavior**
A confirm prompt is shown with no error.

**Platform:**
 - OS: Linux
 - Game version: 98.2.365 (should occur as early as 98.0, not tested)
 - Any other mods/scripts: none

**Comment by Rebmiami** [comment]
Should be fixed in the latest commit
